settings:
  add_gh_comment: true
  components:
  - WordPress
  epic_key: ISD-3981
  jira_project_key: ISD
  label_mapping:
    bug: Bug
    enhancement: Story
  status_mapping:
    closed: done
    not_planned: rejected
    opened: Untriaged
