# This is a workflow to generate materials and run a Spread test on the tutorial

name: 'Test the tutorial with Spread'

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'docs/tutorial.md'

jobs:
  tutorial-spread-test:
    uses: canonical/operator-workflows/.github/workflows/docs_spread.yaml@main
    secrets: inherit
    with:
      input-file: docs/tutorial.md
      output-dir: tests/spread/tutorial/
      spread-job: github-ci:ubuntu-24.04-64:tests/spread/tutorial

