name: Publish to edge

# On push to a "special" branch, we:
# * always publish to charmhub at latest/edge/branchname
# * always run tests
# where a "special" branch is one of sidecar or track/**, as
# by convention these branches are the source for a corresponding
# charmhub edge channel.

on:
  workflow_dispatch:
  push:
    branches:
      - sidecar
      - track/**

jobs:
  publish-to-edge:
    uses: canonical/operator-workflows/.github/workflows/test_and_publish_charm.yaml@main
    secrets: inherit
